name: mllearning-environment
channels:
  - conda-forge
  - anaconda
dependencies:
  - python
  - numpy
  - pandas
  - scikit-learn
  - nltk
  - gensim
  - striprtf.striprtf
  - matplotlib
  - tqdm
  - pyLDAvis
  - seaborn
